services:
  app:
    build:
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped


volumes:
  redis_data:
    
