services:
  app:
    build:
      context: .. 
      dockerfile: services/location-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      SERVICE_NAME: location-service
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped


volumes:
  redis_data:
    
